### ISSUE TITLE
Support including 'discriminated' type values via !inplace

### ISSUE THREAD

**Issue by mikhail-barg** [nictoarch/nictoarch#30]
after #29 it's now possible to write

```yaml
        auth: !inplace values.yaml
```

```yaml
        auth: 
          type: basic
          user: !inplace values.yaml#user
          pass: !inplace values.yaml#pass
```

but not

```yaml
        auth: 
          type: !inplace values.yaml#type
          user: !inplace values.yaml#user
          pass: !inplace values.yaml#pass
```
